### PR TITLE
Multiple bug fixes

### LINKED ISSUE #66: No Boozeomat in the Bar
#### Description of issue
No Booze-O-Mat in the Bar. Also no damp rag. Super minor stuff.

#### Difference between expected and actual behavior
Should be a booze machine in the bar
#### Steps to reproduce
N/A
#### Specific information for locating

N/a

#### Length of time in which bug has been known to occur

N/a

#### Client version, Server revision & Game ID

N/a

#### Issue bingo

- [X] Issue could be reproduced at least once
- [X] Issue could be reproduced by different players
- [X] Issue could be reproduced in multiple rounds
- [X] Issue happened in a recent (less than 7 days ago) round
- [X] [Couldn't find an existing issue about this](https://github.com/HearthOfHestia/Nebula/issues)

### LINKED ISSUE #84: Bridge tints do not work.
#### Description of issue

Pressing the 'Tint Windows' buttons in the bridge do not tint the windows.

#### Difference between expected and actual behavior

yes

#### Steps to reproduce

go to bridge
press tint windows button 
Watch as the windows remain untinted

#### Length of time in which bug has been known to occur

Since the test in 9/26/2021

#### Client version, Server revision & Game ID

Server Revision: Revision Unknown
Game ID: ced-cNpl
Current map: ISEO Endeavour

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

### LINKED ISSUE #85: [FEATURE] Add more alert screens to the decks.
#### Is your feature request related to a problem? Please describe.

The lack of alert screens in the hallways of the Endeavor is annoying. More alert screens are required to convey messages (Such as an EVA Ban), alert levels, and so on.

#### Describe the solution you'd like

Mapping-in more alert screens in the hallways of each deck would be a good thingy

#### Feature bingo

- [x] Feature does not already exist
- [x] Feature has not been rejected in the past 30 days
- [x] Feature has no maintainer vetos
- [x] Feature does not break the [Github Acceptable Use Policies on restricted content](https://docs.github.com/en/github/site-policy/github-acceptable-use-policies#2-content-restrictions)
- [x] [Couldn't find an existing feature request about this](https://github.com/HearthOfHestia/Nebula/labels/enhancement).

### LINKED ISSUE #110: Engineering borgs cannot interact iwth the pipe fabricator. Neither can drones.
#### Description of issue
See title. Cannot open the interface.

#### Difference between expected and actual behavior
To be able to do this.

#### Steps to reproduce
Click on pipe printer. Nothing.

#### Specific information for locating

AI shard, borg, etc. Drones.
11

#### Length of time in which bug has been known to occur

Not a clue.

#### Client version, Server revision & Game ID

Client Version: 514
Server Revision: Revision Unknown
Game ID: cek-dBO9
Current map: ISEO Endeavour

#### Issue bingo

- [ ] Issue could be reproduced at least once
- [ ] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [ ] Issue happened in a recent (less than 7 days ago) round
- [ ] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

### LINKED ISSUE #120: Combustion indicators are useless and can be moved.
#### Description of issue

sippy

You can click and grab combustion indicators.
Additionally, there are no combustion chambers in the nacelles.

#### Difference between expected and actual behavior

The combustion indicators should not exist in the first place without combustion chambers.

#### Steps to reproduce

Go to engineering
Find combustion indicator that shouldn't exist
Control + Click
pull le funny indicator around

#### Specific information for locating

no

#### Length of time in which bug has been known to occur

Since the test at 10/16/2021 (DD/MM/YYYY)

#### Client version, Server revision & Game ID

Client Version: 513
Server Revision: Revision Unknown
Game ID: cex-dG9V
Current map: ISEO Endeavour

#### Issue bingo

- [x] Issue could be reproduced at least once
- [x] Issue could be reproduced by different players
- [ ] Issue could be reproduced in multiple rounds
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] [Couldn't find an existing issue about this](https://github.com/NebulaSS13/Nebula/issues)

### PR DESCRIPTION
**Pull request by Kaksisilma**
## Description of changes

Fixes https://github.com/HearthOfHestia/Nebula/issues/120
Indicators have been removed, along with buttons.

Fixes https://github.com/HearthOfHestia/Nebula/issues/110
Not broken in the first place, but pipe dispensers now start anchored.

Fixes https://github.com/HearthOfHestia/Nebula/issues/85
Alert screens were added inside walls, instead of being pixel-shifted. This has been fixed.

Fixes https://github.com/HearthOfHestia/Nebula/issues/84
IDs were poorly set.

Fixes https://github.com/HearthOfHestia/Nebula/issues/66
Boozemat has been added at the expense of 1 table and 3 mugs.

**DOES NOT FIX** https://github.com/HearthOfHestia/Nebula/issues/42
Opted not to change it and just leave it as-is for the time being.

## Why and what will this PR improve

sdmm go brr

## Authorship

me

### CODE REVIEW

**Comment by Kaksisilma** [comment]
Unrelated CI error.

**Comment by MarinaGryphon** [comment]
> Fixes #42
> Replaced the airlocks by simpler types. Not too proud of this one.

This PR is not getting merged with these changes included.

**Comment by Kaksisilma** [comment]
> 
> 
> > Fixes #42
> > Replaced the airlocks by simpler types. Not too proud of this one.
> 
> This PR is not getting merged with these changes included.

I was unable to find a way to make the airlock controller work. The one in Xenobiology is also non-functional and I am clueless as to why. This is a less-than-elegant solution, yes, but also one that does not obstruct access to the R-UST while fixes are worked-on.

**Comment by Mazianni** [comment]
Now conflicts with master branch due to changes on D2.

**Comment by Kaksisilma** [comment]
Ready for review, again. RUST is kept untouched this time.

**Pull request merged**
